name: C/C++ CI

on:
  schedule:
    - cron: '0 1 */2 * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: update apt
      run: sudo apt-get update
    - name: install deps
      run: sudo apt-get install gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 binutils-mingw-w64 git build-essential autoconf autoconf2.13 automake1.11 libtool
    - name: apply patch
      run: cd file && git apply ../filep.patch
    - name: run build script
      run: ./build.sh
    - name: generate tag
      id: tag
      run: |
        echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: ./dist/*
